apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          command: ["bash", "-c", "sleep 900"]
          image: ubuntu:20.04
